/**
 * Generated by AppClaw goal mode — a replayable starting point, not a final test.
 *
 * Original goal: open youtube app and search for appium 3.0
 * Steps recorded: 3 (from 6 agent steps)
 *
 * Caveats — read before running this in CI:
 *
 * 1. Replay does not have the goal-mode safety net. In goal mode the agent
 *    re-checks the screen after each step, retries failed actions, and adapts
 *    when the UI is in an unexpected state. `app.run(...)` calls below do none
 *    of that — each step fires once and moves on. If a step worked on the
 *    second try in goal mode, it may need an explicit `app.run('wait 2 seconds')`
 *    or a `app.verify(...)` checkpoint here before the next step.
 *
 * 2. Failed/recovered steps were filtered out, so the count above may differ
 *    from what you saw in the live run.
 *
 * 3. Coverage is best-effort. The translator (sdk/goal-export.ts) maps a fixed
 *    set of agent tools to natural language. Any newer agent tool that isn't
 *    in that map is silently skipped — if your replay is missing a step,
 *    cross-check against the AgentResult.history.
 *
 * 4. Edit freely. Treat this file as a draft: rename the test, add assertions
 *    (`app.verify(...)`), tighten selectors, split into multiple `it()` blocks.
 */
import { AppClaw } from '@appclaw/core';
import { describe, it } from 'vitest';
import 'dotenv/config';

describe('Recorded flow', () => {
  it("tap first suggestion 'appium 3.0' with history icon", async () => {
    const app = new AppClaw({
      provider: 'gemini',
      apiKey: process.env.LLM_API_KEY,
      platform: 'android',
      agentMode: 'vision',
    });
    await app.run('open YouTube app');
    await app.run('tap magnifying-glass search icon in the top right corner');
    await app.run('type "appium 3.0" into search edit field with hint \'Search YouTube\' at top');
    await app.run("tap first suggestion 'appium 3.0' with history icon");

    await app.teardown();
  }, 120000);
});
