/**
 * Generated by AppClaw — a replayable starting point, not a final test.
 *
 * Source: AppClaw playground
 * Steps recorded: 4
 *
 * Caveats — read before running this in CI:
 *
 * 1. Each step is the verbatim text you typed in the playground — exactly
 *    what `AppClaw.run()` will receive. There is no translator in between,
 *    so the replay should behave identically to the playground session.
 *
 * 2. Selectors are still locator strings, not stable IDs. If the app UI
 *    changes (icons relabelled, layout shifts), the natural-language
 *    selectors above may need updating.
 *
 * 3. Edit freely. Treat this file as a draft: rename the test, add
 *    assertions (`app.verify(...)`), split into multiple `it()` blocks.
 */
import 'dotenv/config';
import { describe, it } from 'vitest';
import type { RunOptions } from '@appclaw/core';
import { AppClaw } from '@appclaw/core';
describe('Recorded flow', () => {
  it('launches vodqa and swipe the first slider to the right', async () => {
    const app = new AppClaw({
      apiKey: process.env.LLM_API_KEY,
      platform: 'android',
      video: true,
      mcpDebug: true,
      silent: true,
      waitTimeout: 10000,
      waitInterval: 1000,
      locatorCache: true,
      capabilitiesFile: './tests/caps.json',
    });

    await app.run('open vodqa app');
    await app.run('click on login button');
    await app.run('click on Vertical swiping');
    await app.run('scroll down 2 times until Karma is visible', {
      scrollMode: 'short',
    } as RunOptions);
    await app.verify('if the text Karmaaa is visible');
    await app.teardown();
  }, 120000);
});
